### ISSUE TITLE
Creates a Precipitation Map

### ISSUE THREAD

**Issue by Creutzx** [Creutzx/PrecipMap#1]
This code adds precipitation, watershed outline, and a streams layer to a "blank" .mxd file.

Some details that I want to mention are:

- as best I can tell, it isn't possible to add a scale bar and north arrow to a blank .mxd file using ArcPy. It is possible to manipulate them once they are in the "blank" .mxd file. If you know of a way to do this, let me know. This is similar to the problem I encountered with trying to create a blank .mxd file out of thin air. Comments ran along the lines of: ArcPy can be used to manipulate map elements, layers, etc. within an existing .mxd file, but can't create them (i.e., you have to create a blank map document first).

- this code eliminates all the legend elements except precipitation.

- If we want to eliminate the jagged edges of the precipitation raster, maybe I could add a masking layer to go over a square shaped raster. Or maybe there's another way to deal with this that you know of?

Let me know if there's anything else!

**Comment by kbrannan** [comment]
This looks good.

For the precip raster, how are you extracting the data for the watershed? Respond in a replay to this message with the steps you did as a numbered list.

For the map layout in the blank mxd, I suggest adding the watshed boundary and the NHD data. Then you could adjust the positon of the scale and other items manually and it should work for the maps you make automatically. Once you make those changes, rerun the script to make the map and tell me what mxd you want me to review.

**Comment by Creutzx** [comment]
I clipped the Upper Yaquina precipitation raster from the PRISM 1981-2010 average annual precip dataset.

1) we didn't have the most recent PRISM data in the base data library so I downloaded a local copy
2) I then used Arc Toolbox (Data Management>>Raster>>Raster Processing>>Clip) to clip the nationwide raster with the official upper yaquina HUC 10 you provided me.
3) I did step #2 both with and without the "Use Input Features for Clipping Geometry" box checked.
4) Without the box checked, I got a rectangular raster that would need to have a mask in order to not see the area outside the watershed.
5) With the box checked, I ended up with the jagged edges you can see in this layer file:

\\DEQHQ1\TMDL\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\UY_Precip.lyr

Regarding the changes to the code you describe in the last paragraph of your comment, I'll start working on that right now and will let you know when that's done.

**Comment by kbrannan** [comment]
Make a version of the map with raster in step 4 and let me take a look at it.

**Comment by Creutzx** [comment]
Here you go:

\\DEQHQ1\TMDL\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_UY_Precip.mxd

**Comment by kbrannan** [comment]
Ok, if you use a mask, make it the inverse of the Upper Yaquina Watershed boundary.

**Comment by kbrannan** [comment]
Another option is to create a buffered polygon for the watershed boudary and use that to clip the rater. I am not concerned about the raster cells outside the boudary. I want all the area within the watershed boundary to have precip data

**Comment by Creutzx** [comment]
Let me know if this works:

\\DEQHQ1\TMDL\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_Layout_Precip_BRC.mxd

If there's a version with smaller pixels, or a better way to do this, just let me know.

**Comment by kbrannan** [comment]
That's great. Rename the Big_square shapfile to "Inverse-upper-yaquina-river-huc-10.shp" and rename the layer in the TOC to "HUC 10 Mask"

**Comment by Creutzx** [comment]
Done. Now going back to working on the code.

**Comment by kbrannan** [comment]
great
