### ISSUE TITLE
Updated blank .mxd file

### ISSUE THREAD

**Issue by Creutzx** [Creutzx/PrecipMap#3]
From the earlier thread you wrote:

_For the map layout in the blank mxd, I suggest adding the watshed boundary and the NHD data. Then you could adjust the positon of the scale and other items manually and it should work for the maps you make automatically. Once you make those changes, rerun the script to make the map and tell me what mxd you want me to review._

Here's what it looks like after I ran the script:

\\DEQHQ1\TMDL\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_UY_Precip.mxd

**Comment by kbrannan** [comment]
Looks great. now do the same process for the elevation map.

Create a new repository for the work in the levation map

**Comment by Creutzx** [comment]
The new repository with the elevation script is open and I sent you an invite. The elevation map that is created by the script is located here:

\\DEQHQ1\TMDL\TMDL_WR\MidCoast\GIS\Figures\Upper_Yaquina_Maps\Upper_Yaquina_TMDL_UY_Elev.mxd

I used one of the colorblind-friendly color ramps for this, but can change it to grayscale (or whatever you think it should be).
